name: demo_ai_even
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 11.4.0
  sqflite: ^2.4.1
  path: ^1.9.0

  # Core Packages
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  dio: ^5.4.3+1
  get: ^4.6.6
  path_provider: ^2.1.3
  crclib: ^3.0.0
  soundpool: ^2.3.0
  google_fonts: ^6.3.0
  confetti: ^0.8.0
  lottie: ^3.2.0
  fl_chart: 0.63.0
  percent_indicator: ^4.2.5
  flutter_staggered_animations: ^1.1.1

  # For OpenAI API
  dart_openai: ^5.1.0

  # For Native Speech-to-Text
  record: ^6.0.0
  record_platform_interface: ^1.3.0
  record_linux: ^1.1.1
  
  # For Deepgram Speech-to-Text
  deepgram_speech_to_text: 3.1.0
  # For Secure API Key Management
  flutter_dotenv: 5.2.1
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3
  just_audio: ^0.9.36 # Replaced audioplayers
  vibration: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/vocab.txt
    - assets/sounds/
    - assets/anim/
    - assets/interview/

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: assets/icons/app_icon.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/icons/app_icon.png
    background_color: "#121212"
    theme_color: "#121212"
  macos:
    generate: true
    image_path: assets/icons/app_icon.png
  windows:
    generate: true
    image_path: assets/icons/app_icon.png
